[package]
name = "codecrafters-shell"
version = "0.1.0"
authors = ["Codecrafters <hello@codecrafters.io>"]
edition = "2021"
rust-version = "1.80"

[dependencies]
anyhow = "1.0.95"                                # error handling
bytes = "1.10.0"                                 # helps manage buffers
thiserror = "2.0.11"                             # error handling
